"""
Django settings for ConnectionHub project.
Generated by 'django-admin startproject' using Django 4.1.7.
"""

from pathlib import Path
import os
import environ
from cryptography.fernet import Fernet

# ------------------------------------------------------------------
# BASE DIRECTORY
# ------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------
# ENVIRONMENT VARIABLES (FIXED FOR WINDOWS)
# ------------------------------------------------------------------
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# ------------------------------------------------------------------
# SECURITY
# ------------------------------------------------------------------
SECRET_KEY = env('SECRET_KEY', default='django-insecure-local-dev-key')
DEBUG = env('DEBUG', default=True)
ALLOWED_HOSTS = ['*']

# ------------------------------------------------------------------
# APPLICATIONS
# ------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Project apps
    'Home.apps.HomeConfig',
    'Users.apps.UsersConfig',
    'Posts.apps.PostsConfig',
    'Reports.apps.ReportsConfig',
    'Auth.apps.AuthConfig',
    'Comments.apps.CommentsConfig',
    'Help.apps.HelpConfig',
    'Communications.apps.CommunicationsConfig',
    'UsersSettings.apps.UserssettingsConfig',
    'Notifications.apps.NotificationsConfig',

    # Admin apps
    'Admin.AdminHome.apps.AdminhomeConfig',
    'Admin.AdminHelp.apps.AdminhelpConfig',
    'Admin.AdminPost.apps.AdminpostConfig',
    'Admin.AdminReports.apps.AdminreportsConfig',
    'Admin.AdminUsers.apps.AdminusersConfig',

    # Channels
    'channels',
]

# ------------------------------------------------------------------
# MIDDLEWARE
# ------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------------------------
# URLS / ASGI
# ------------------------------------------------------------------
ROOT_URLCONF = 'ConnectionHub.urls'
ASGI_APPLICATION = 'ConnectionHub.asgi.application'

# ------------------------------------------------------------------
# TEMPLATES
# ------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------------------------------------------------
# DATABASE (SQLITE FOR LOCAL DEVELOPMENT)
# ------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------------------------------------------
# AUTH / PASSWORDS
# ------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'Users.User'

# ------------------------------------------------------------------
# INTERNATIONALIZATION
# ------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------
# STATIC & MEDIA
# ------------------------------------------------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ------------------------------------------------------------------
# EMAIL (SAFE DEFAULTS)
# ------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = env('EMAIL_ADDRESS', default='test@example.com')
EMAIL_HOST_PASSWORD = env('EMAIL_PASSWORD', default='dummy')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='test@example.com')

# ------------------------------------------------------------------
# CHANNELS
# ------------------------------------------------------------------
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# ------------------------------------------------------------------
# ENCRYPTION (FERNET)
# ------------------------------------------------------------------
FERNET_KEY = env('FERNET_KEY', default=Fernet.generate_key().decode())
cipher_suite = Fernet(FERNET_KEY.encode())

# ------------------------------------------------------------------
# DEFAULT AUTO FIELD
# ------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
